<?php

namespace headflow\core\widget\layout;

require_once dirname(__FILE__) . '/../../../../../../../hfbase/headflow/core/widget/layout/GridLayout.php';

/**
 * Test class for GridLayout.
 * Generated by PHPUnit on 2011-05-23 at 02:40:17.
 */
class GridLayoutTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var GridLayout
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GridLayout;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     *
     */
    public function testSave(){
        $img = new \headflow\core\widget\base\Image();
        $img->setImagePath('TestImage.jpg');
        $this->object->addChild($img);
        $this->object->addChild(new \headflow\core\widget\base\HtmlText());
        $this->object->save();
        return $this->object;
    }

}

?>
