<?php

namespace headflow\core\widget;

require_once dirname(__FILE__) . '/../../../../../../hfbase/headflow/core/widget/Widget.php';

/**
 * Test class for Widget.
 * Generated by PHPUnit on 2011-05-22 at 01:47:55.
 */
class WidgetTest extends \PHPUnit_Framework_TestCase {


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    /**
     * 
     */
    public function testLoad() {
        $image =  new base\Image();
        $this->assertNotNull($image);
        $image->setAltText("Alt Text");
        $image->setTitle("Title");
        $image->setImagePath("test.png");
        return $image;
    }

    /**
     * @todo Implement testFindWhere().
     */
    public function testFindWhere() {

    }

    /**
     * @todo Implement testLoadAll().
     */
    public function testLoadAll() {
  
    }

    /**
     * @depends testLoad
     */
    public function testSave($widget) {
        $widget->save();
        return $widget;
    }

    /**
     * @depends testSave
     */
    public function testDelete($widget) {
        $widget->delete();
    }


}

?>
