<?php 
namespace codegeneration;


class CodeGenerationConfig {
	
	/**
	 * @var string $template the name of the template. 
	 */
	public $template;
	
	/**
	 * The path to the file that should be generated by the template. 
	 * You can use %entityName% and %entityClass% and the will be replaced with the proper value during code generation. 
	 * @var string $fileOutputPath
	 */
	public $fileOutputPath;
	
	/**
	 * 
	 * @var Boolean if true then the output file will be replaced if it exists false and it will be skipped. 
	 */
	public $replaceFileIfExists;
	
	/**
	 * @var IParameterGenerator
	 */
	public $parameterGenerator;
	
	
	function __construct($template,$fileOutputPath,IParameterGenerator $parameterGenerator, $replaceFileIfExists=false){
		$this->template = $template;
		$this->fileOutputPath = $fileOutputPath;
		$this->parameterGenerator = $parameterGenerator;
		$this->replaceFileIfExists = $replaceFileIfExists;
	}
	
}


?>